name: Build V8 on macos

on: push

env:
  V8_VERSION: 9.9.115.9

jobs:
  build:
    name: Build V8 on ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-10.15]
        python-version: ["3.9"]
    runs-on: ${{matrix.os}}

    steps:
      - name: step1, checkout repo
        uses: actions/checkout@v2
